### ISSUE TITLE
Can we use the shapefiles of the deleted redaction data? 

### ISSUE THREAD

**Issue by Rub21** [osm-pe/osm-peru-redaction#2]
According to @naoliv, he could give us a shapefile of the removed data after the osm redaction, would be good to use that data to make a TMS layer to use in JOSM background as a guide to check where was the places where were affected.

- Could we use the deleted data of the redaction as a guide to improve OSM?   is it allowed?

cc. @piligab

**Comment by naoliv** [comment]
We can't retrace the objects using the redacted streets (ie, we can't use their geometries and/or names), since we will be deriving products from a source that we are not allowed to use.

The shapefiles/GeoJSON are based on the areas where the objects were affected.
For example:
![](https://user-images.githubusercontent.com/982338/35644692-cf454ce4-06b0-11e8-883c-30ad281f9c75.png)

Maybe I can include some numbers inside these areas, to help in identifying them.
For example, we could calculate the number of streets with a `name` inside them or the amount of streets (regardless if they have a `name` or not).

An area with a high number of named streets (which were affected) could indicate that it's from a city (and that should be mapped first).

**Comment by Rub21** [comment]
@naoliv that is good to know and also the geojson-polygons is good enough to identify those affected places!

**Comment by vespax** [comment]
Will/Would the DWG extract the 'good' data and preserve it to be reapplied to new geometry?  For example, any data added with in the past 4 to present time period, which would be good contributions by the community, despite those tags being placed onto the infringing/bad data.

**Comment by naoliv** [comment]
@vespax please, contact the DWG through data@osmfoundation.org for technical and legal questions related with this redaction.

**Comment by piligab** [comment]
No more actions here!
